services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/atmosfair-db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Map port 5173 (where Vite runs) to port 5173 on the host
    depends_on:
      - backend
    restart: always

  mongodb:
    image: mongo
    container_name: hvac-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
