services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Map port 5173 (where Vite runs) to port 5173 on the host
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:latest
    container_name: hvac-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hvac_scheduler
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
