version: "3.9"

services:
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: always
    ports:                         # ← add this block
    - "27017:27017"   

  backend:
    build: ./backend          # your Dockerfile exposes 5000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/atmosfair-db
    depends_on:
      - mongodb
    restart: always
    ports:             #  ← add
    - "5001:5000"                # only inside the compose network

  frontend:
    build:
      context: ./frontend
      target: production      # make the Dockerfile build a static bundle
    restart: always
    expose:
      - "80" 
    ports:
      - "3005:80"     # hostPort:containerPort   ← ADD THIS                 # container runs nginx:alpine and serves dist

networks:
  default:
    name: atmosfair_net

volumes:
  mongo-data:
